export const carDatabase = [
  {
    name: "BMW",
    id: "1",
    Image: "/images/BMW.svg.png",
    link: "/search",
  },
  {
    name: "Ferrari",
    id: "2",
    Image: "/images/ferrari.png",
    link: "/search",
  },
  {
    name: "Fiat",
    id: "3",
    Image: "/images/FIAT.png",
    link: "/search",
  },
  {
    name: "Ford",
    id: "4",
    Image: "/images/Ford-Motor-Company-Logo.png",
    link: "/search",
  },
  {
    name: "Mercedes",
    id: "5",
    Image: "/images/Mercedes-Logo.svg.png",
    link: "/search",
  },
  {
    name: "Huyundai ",
    id: "6",
    Image: "/images/Hyundai.png",
    link: "/search",
  },
  {
    name: "Tesla ",
    id: "7",
    Image: "/images/tesla.png",
    link: "/search",
  },
];

export const cars = [
  {
    name: "Toyota Corolla",
    id: "1",
    isAutomatic: "Manual",
    tireType: "All-Season",
    fuelUsage: "8 L/100km",
    dailyRent: "$45",
    image: "/CarModels/Toyota.png",
  },
  {
    name: "Ferrari",
    id: "2",
    isAutomatic: "Automatic",
    tireType: "All-Season",
    fuelUsage: "7.5 L/100km",
    dailyRent: "$40",
    image: "/CarModels/Ferrari.png",
  },
  {
    name: "Fiat",
    id: "3",
    isAutomatic: "Manual",
    tireType: "Performance",
    fuelUsage: "12 L/100km",
    dailyRent: "$90",
    image: "/CarModels/Fiat.png",
  },
  {
    name: "Chevrolet Tahoe",
    id: "4",
    isAutomatic: "Manual",
    tireType: "All-Terrain",
    fuelUsage: "14 L/100km",
    dailyRent: "$100",
    image: "/CarModels/Chevrolet Tahoe.png",
  },
  {
    name: "Volkswagen Golf",
    id: "5",
    isAutomatic: "Automatic",
    tireType: "All-Season",
    fuelUsage: "6.5 L/100km",
    dailyRent: "$50",
    image: "/CarModels/Volkswagen.png",
  },
  {
    name: "BMW 3 Series",
    id: "6",
    isAutomatic: "Manual",
    tireType: "Performance",
    fuelUsage: "9 L/100km",
    dailyRent: "$85",
    image: "/CarModels/BMW.png",
  },
  {
    name: "Mercedes-Benz C-Class",
    id: "7",
    isAutomatic: "Manual",
    tireType: "Performance",
    fuelUsage: "9.5 L/100km",
    dailyRent: "$95",
    image: "/CarModels/Mercedes.png",
  },
  {
    name: "Hyundai Elantra",
    id: "8",
    isAutomatic: "Automatic",
    tireType: "All-Season",
    fuelUsage: "7 L/100km",
    dailyRent: "$35",
    image: "/CarModels/Hyundai Elantra.png",
  },
  {
    name: "Tesla Model 3",
    id: "9",
    isAutomatic: "Manual",
    tireType: "All-Season",
    fuelUsage: "Electric",
    dailyRent: "$120",
    image: "/CarModels/Tesla Model 3.png",
  },
  {
    name: "Nissan Altima",
    id: "10",
    isAutomatic: "Manual",
    tireType: "All-Season",
    fuelUsage: "8 L/100km",
    dailyRent: "$55",
    image: "/CarModels/Nissan Altima.png",
  },
];
